services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit
      - TZ=Europe/Moscow

